// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uogysnwigplndidllwvh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvZ3lzbndpZ3BsbmRpZGxsd3ZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2OTI1MDEsImV4cCI6MjA2NDI2ODUwMX0.9EZMyoIlHZQiF6uJVQpHsqzzok4JQTTShpSvTdCYGWc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);